[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración para Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"

# NOTA: Las variables de entorno deben configurarse en el dashboard de Netlify
# No incluimos valores hardcodeados aquí por seguridad
# Variables requeridas:
# - NEXT_PUBLIC_SUPABASE_URL
# - NEXT_PUBLIC_SUPABASE_ANON_KEY  
# - NEXT_PUBLIC_APP_URL
